### ISSUE TITLE
Simplify code in Infection API

### ISSUE THREAD

**Issue by csleead** [Covid-19Radar/Covid19Radar#115]
This code can be simplified.
https://github.com/Covid-19Radar/Covid19Radar/blob/1dfc09a77f8129482c9f7234fa9f8db16704432c/src/Covid19Radar.Api.External/InfectionApi.cs#L97-L119

**Comment by darkcrash** [comment]
@csleead 
Thank you.
This API is also raised to another Issue, but it will be an API of a completely different specification.

**Comment by csleead** [comment]
@darkcrash 
In this case, I am not sure whether this issue is valid. Just close this issue if that's the case.

**Comment by darkcrash** [comment]
thank you for your pull request.

There is only one point.
Beacon data must be verified to be bidirectional.
This is because it includes cases where one is registered with incorrect data. To solve this, I decided to generate a "Contact Document Collection" in CosmosDB.

However.
We have undergone a fundamental review of the treatment of personal data.
We have come to the conclusion that we need a mechanism to move independently with local data that does not collect data.

**Comment by darkcrash** [comment]
@csleead 
The infection and contact update process will be reworked for me in the near future.
I'm sorry i didn't get through pullrequest. Thanks
