### ISSUE TITLE
Move to Cosmos Graph API

### ISSUE THREAD

**Issue by tomkerkhove** [Covid-19Radar/Covid19Radar#182]
Great work but would be good to move to Cosmos Graph API to leverage full power of the data layer.

**Comment by kazumihirose** [comment]
Thank you for good idea!
We were initially CosmosDB.
We are thinking about the average number of concurrent requests per second and the Cosmos DB costs associated with them.
Also, since it was made anonymous by Exposure Notification and visualization by graph DB became difficult, now we are using Azure Storage Blob.
