### ISSUE TITLE
Tutorial page 5 does not set a icon for notifications.

### ISSUE THREAD

**Issue by kenz** [Covid-19Radar/Covid19Radar#568]
**Describe the bug**
White tofu show in the notification

**To Reproduce**
1. Start app.
2. Proceed with the tutorial.
3. Tap the Turn on in page of "to use notifications".
4. White tofu show in the notification
1. アプリを起動します。
2.チュートリアルを進めます
3.通知をご利用いただくために のページで有効にするをタップします
4.白い豆腐が通知に表示されます

**Screenshots**
![Screenshot_20200622-061900](https://user-images.githubusercontent.com/479696/85235662-db21d680-b451-11ea-899e-d5a4a26743af.png)

**Smartphone (please complete the following information):**
 - Device: Pixel3
 - OS: Android 11 beta

**Additional context**
Please set an icon to the notification.
通知にアイコンをセットしてください。

**Comment by chooyan-eng** [comment]
This problem can be solved by adding properties below to 'new NotificationRequest'

```
Android =
{
    IconName = "my_icon"
}
```

**See:** 
https://github.com/thudugala/Plugin.LocalNotification/wiki/%5BAndroid%5D-How-to-change-notification-icon

One thing which have to be decided is the icon file to show. (Logo.png?)
If `Logo.png` should be used, file name must be lower_snake_case, otherwise tofu is still on screen.

See: 
https://stackoverflow.com/questions/39439586/why-doesnt-android-allow-you-to-have-capital-letters-in-resource-names

When I tried `IconName = "Logo"` it didn't work, but `IconName = "logo_notification"` worked.

**Comment by chooyan-eng** [comment]
The screenshot of showing `Logo.png` as notification icon is below.

![Screenshot_1592822462](https://user-images.githubusercontent.com/20849526/85279912-283d9100-b4c2-11ea-8416-3c29c644251f.png)

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
However, I would like to consider it on Covid19Radar as it is a very appreciated proposal.
and already fixed this issue.
