### ISSUE TITLE
"陽性情報の登録と他者への匿名通知へ" may be truncated when an user employs larger text.

### ISSUE THREAD

**Issue by Niccari** [Covid-19Radar/Covid19Radar#589]
**Describe the bug**
Some button texts, especially "陽性情報の登録と他者への匿名通知へ" may be truncated when user employs larger text. This may well be the case for users who have difficulty seeing, as they often use larger text.

**To Reproduce**
1. Set the Dynamic Type to 5 of 7.
2. Open "使い方" > "新型コロナウイルスに感染していると判定されたら".
3. Scroll down to bottom.

**Expected behavior**
Button text should be fully shown.

**Screenshots**
* Correct(Dynamic Type: 2 of 7, default)
![Simulator Screen Shot - iPhone 11 - 2020-06-22 at 21 44 54](https://user-images.githubusercontent.com/30116202/85289513-8a05f700-b4d2-11ea-886f-e29c27892ed5.png)

* Truncated(Dynamic Type: 6 of 7)
![Simulator Screen Shot - iPhone 11 - 2020-06-22 at 21 44 15](https://user-images.githubusercontent.com/30116202/85289777-e8cb7080-b4d2-11ea-9029-b662edd4abaa.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11(Simulator)
 - OS: iOS 13.5.1
 - Browser safari
 - Version commit: (https://github.com/Covid-19Radar/Covid19Radar/commit/412d0f4221d364da8b792b1eb602fd277957bcb1)

**Additional context**
In this case, "と他者への匿名通知へ" is not needed and should be deleted.

In the UI, the button should only indicate a user action. The system does anonymous notification automatically, and it is not the user's action. Also, the page description already explains that others are notified anonymously, so this is redundant.

**Comment by nacho4d** [comment]
I use the app in english/spanish/japanese and some button texts are truncated like this. This is not an specific problem of Dynamic Font. It is because button's height seems to be hardcoded.

Question for lead engineer, lead designer,

If we fix this, what is the pattern we should follow at moment of fixing this? 
a) Allow various lines in the button so button will grow vertically? (Are designers OK with this approach?)
b) Try to make the font smaller to fit the button max width? (Sometimes it affects readability)
c) Think of a better shorter string? (Sometimes it is not possible)

こんにちは、私はOS言語を外国語にすることが多くて　時々ボタンのテキストはこんな感じになってしまいます。スペイン語最近翻訳されて英語より大抵長くて　今後この状況がより表面化されると思います。

（元々日本向けのアプリで日本語がメインの理解していますが　日本語ではなく母国語で読みたい日本にいる外国人や上記のように DynamicFontを設定している人もいるので修正した方が良さそうですね。）

リードエンジニア、リードデザイナーの方へ、

もし修正した場合は方針を聞かせていただければ幸いです。どのように修正するのが望ましいでしょうか？

a) 文言に応じてボタンの高さを伸ばす？ (デザイナーの方にとって問題ないでしょうか？)
b) フィットするようにフォントを小さく設定する？（readibilityに影響与えることがある）
c) 短い文言を何とかして考える (本当に無理な時があって)

教えていただければ幸いです。 😸 

<img src="https://user-images.githubusercontent.com/111651/85298494-20d8b080-b4df-11ea-93e2-4dfaf544e5fa.png" alt="alt text" width="250"><img src="https://user-images.githubusercontent.com/111651/85298500-23d3a100-b4df-11ea-9de8-a37fb433963c.png" alt="alt text" width="250"><img src="https://user-images.githubusercontent.com/111651/85298969-abb9ab00-b4df-11ea-9bcf-e4efedd8344f.png" alt="alt text" width="250">

**Comment by CH3COOH** [comment]
Androidでフォントサイズを大きくした場合、ボタンのラベルは複数行に改行されて表示されています。

![Screenshot_20200623-001619_COVID-19 Contact App](https://user-images.githubusercontent.com/137952/85304646-f12da680-b4e6-11ea-8896-ff100c280d0a.jpg)

本アプリでのデザインの縛りには詳しくありませんが、iOSでも文字数が長い場合やフォントサイズを大きくした場合には、ボタンのラベルが複数行で表示されても良いように思えます。

Device: Galaxy A7
OS: Android 9

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
