### ISSUE TITLE
[Android] still getting notifications after uninstallation

### ISSUE THREAD

**Issue by funwarioisii** [Covid-19Radar/Covid19Radar#728]
**Describe the bug**
I've uninstalled the app, but I'm still getting app notifications
Specifically, you'll be notified when you turn off Bluetooth on your smartphone.

**To Reproduce**
1. turn on Bluetooth.
2. uninstall the app.
3. turn off Bluetooth.

**Expected behavior**
please clean up with uninstallation, do not send notification.

**Screenshots**
![Screenshot_20200705-205038~3.png](https://user-images.githubusercontent.com/20943066/86532178-c558ea80-bf02-11ea-9175-1f906012f1e8.png)

when tap the notification, it will appears.
![Screenshot_20200705-205802.png](https://user-images.githubusercontent.com/20943066/86532122-54193780-bf02-11ea-847d-dc60827ceca4.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.

Since the application does not show a notification, it will be a setting unique to the OS.
