### ISSUE TITLE
Review and update translation in English

### ISSUE THREAD

**Issue by YuikoIto** [Covid-19Radar/Covid19Radar#750]
**Is your feature request related to a problem? Please describe.**
英語の翻訳部分の修正

**Describe the solution you'd like**
多言語化をより充実させる

**Describe alternatives you've considered**
機械翻訳の部分が少し変なのでわかりやすく修正&正しい部分もneeds-review-translationのままなのでstatusのチェック。

**Additional context**

**Comment by amouro** [comment]
@YuikoIto Not an important comment to your contribution. I just find the title of this issue is incorrect.

The `-Hant` is only for `zh-Hant`. It is a additional attribute for Chinese (中国語) especially for Traditional Chinese (繁體中文) that used in Taiwan and Hong Kong. There is also `zh-Hans` for Simplified Chinese.

This also applies to #752

**Comment by YuikoIto** [comment]
@amouro Ahh thank you!! I really didn't understand the meaning 'Hant' and guessed that it means Language or something similar!! lol Thank you for correcting my mistakes :)

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
However, I would like to consider it on Covid19Radar as it is a very appreciated proposal.
